### ISSUE TITLE
Following Unity Package Manager format.

### ISSUE THREAD

**Issue by valyard** [backtrace-labs/backtrace-unity#12]
Hi.

At the moment the package is not following UPM format and fails to install from the Package Manager in 2019.3. [Documentation](https://docs.unity3d.com/Manual/CustomPackages.html) describes the format and where various files should go.

In [this fork](https://github.com/valyard/backtrace-unity), I moved files around so now the package is usable with the Package Manager and can be installed directly from the git repo.

My main question right now is why do you need the whole JSON parsing library for the package? Shouldn't the built-in API be enough?
1. It's not really a good idea to drag into the game such a large JSON lib.
2. But if needed, you might want to put it as a dependency to one of the forks like [this one](https://github.com/jilleJr/Newtonsoft.Json-for-Unity).

**Comment by konraddysput** [comment]
Hi,
Thanks for you suggestions with UPM format support!

According to you question with JSON parsing library:
1. Backtrace require to include unstructured data in dictionary, which is not possible with Unity built-in serialization library. Dictionary data structure isn't supported,
2. We forked library to provide few modifications.


If we will be able to serialize dictionary data structure or you have a suggestion how we serialize/deserialize dictionaries in library, we will be able to remove JSON.NET dependency and start using Unity JSON library. Do you have any suggestions how we can achieve that?

**Comment by valyard** [comment]
This is correct, Dictionary serialization is not supported.

In Unity, as a workaround people usually serialize a list of keys and a list of values separately. This is a rather ugly solution and requires post-processing on the server.

But do you really need a Dictionary here? Don't you know the data format you are going to send beforehand? In this case, you can make a class with all the required properties, fill it with data and serialize this class using Unity API.

**Comment by konraddysput** [comment]
User can dynamically decide which one attribute should be included in the Backtrace Report based on the application flow. Because of that, we won't know exactly how attributes will looks like. In addition to that, we allow our users to collect unstructured values from the game/system - like environment variables/ exception properties.


To be clear - we're working on solution to replace JSON.NET library with our lightweight solution. This is on our plugin roadmap and you can expect more updates from us soon.

**Comment by sbahra** [comment]
Thanks for the detailed feedback, working on addressing all of this. Chiming in just so we summarize next steps on our side right now:

UPM packaging release is up or will be up shortly! Here's what's coming up next:
- We'll be moving off of the Unity JSON.NET fork that we have to something lighter-weight to reduce bundle size and improve performance further.
- We're in agreement on the dictionary usage, will move to convenient alternative or a more type-constrained variant.

**Comment by valyard** [comment]
Check out how Unity User Reporting project uses Simple JSON.
https://github.com/facebook-csharp-sdk/simple-json

Judging by my tests, the current Backtrace plugin adds 2MB of IL2CPP metadata to an empty Android project. When trying to fit into over the air install size limits every MB counts.

**Comment by konraddysput** [comment]
@valyard thanks for your suggestion. We're working on the solution now. Please expect more updates from us soon.

**Comment by konraddysput** [comment]
Hey @valyard 

Today we pushed version 2.1.0 with UPM format support. You can check our changes on master branch. 

We started migration from JSON.NET as well. You can see our progress here: https://github.com/backtrace-labs/backtrace-unity/tree/feature/jsonSerializer

**Comment by valyard** [comment]
Cool, installing from the Package manager works now.

**Comment by konraddysput** [comment]
Hey @valyard 

Today we released an alpha version of our Unity plugin without JSON.NET dependency. If you don't mind - this topic suggests changes to UPM format meanwhile, our conversation right now is about JSON.NET. 
Alright if we close this out or was there a specific need or problem that we still should discuss?

**Comment by valyard** [comment]
Right, the original issue is resolved.
