### ISSUE TITLE
ANRs not detected

### ISSUE THREAD

**Issue by IgorGalimski** [backtrace-labs/backtrace-unity#141]
Hi!
I use backtrace version 3.7.1, Unity 2020.3.20f1
I try to detect next ANR
<img width="781" alt="Screenshot 2021-12-03 at 3 49 28 PM" src="https://user-images.githubusercontent.com/19680568/144613234-cfcf1b7a-bffe-46bb-b45d-dd7c54d3f21b.png">

I have next configuration code
<img width="800" alt="Screenshot 2021-12-03 at 3 49 50 PM" src="https://user-images.githubusercontent.com/19680568/144613289-a64ebc11-e62e-4022-8d58-89abec07b163.png">

On device I see it as ANR

![Screenshot_20211203-104839_TestBacktrace](https://user-images.githubusercontent.com/19680568/144613581-a0170ec5-fec7-4117-90a3-5bc67c789415.jpg)

And then I close it. But I don't see this ANR in the console. Is something wrong with my configuration?

**Comment by konraddysput** [comment]
hey @IgorGalimski 

We just detected it and new updates that we're adding to version 3.7.2 should fix this problem. Thank you for this information. I will back to you when we will be ready to release a new version :)

**Comment by IgorGalimski** [comment]
Hey @konraddysput 
Thanks a lot!

**Comment by konraddysput** [comment]
hey @IgorGalimski 

Today we've released a new version of the backtrace-unity plugin that should fix your problem. Closing the issue for now, if you still have any problem with ANR detection, feel free to reopen it :) Thanks!
