### ISSUE TITLE
Unable to find Backtrace in package manager

### ISSUE THREAD

**Issue by nipundavid** [backtrace-labs/backtrace-unity#146]
Hi Team,

I followed the instruction on the installation page - https://help.backtrace.io/en/articles/2484637-unity-integration-guide

1. Downloaded the latest release of backtrace from git (unzipped)
2. Open Package manager in Unity3D>click on top left corner (+) > Add package from disk> Load the JSON file in the backtrace folder
3. Waited for some time to complete loading 

after executing the above steps multiple time even then I didn't find the backtrace in package manager. Is there anything that i am missing?

Unity3D ver - 2019.4.28f
![Screenshot 2021-12-14 at 4 55 45 PM](https://user-images.githubusercontent.com/2108309/145989830-5b2d829d-154c-43fc-a2bb-5f7be6421a91.png)
1

**Comment by konraddysput** [comment]
@nipundavid 
on the right, you have a filter that indicates you're displaying packages only from the Unity registry. If you change the `Unity registry` option to for example "Your assets" you still can't find the Backtrace-Unity package on the list?

**Comment by nipundavid** [comment]
No still not there...But weird thing is that I can find the backtrace client script in search when clicked on add component on a game object in the scene (second screenshot).

<img width="689" alt="Screenshot 2021-12-14 at 6 32 34 PM" src="https://user-images.githubusercontent.com/2108309/146003392-3e7c9680-d5cd-4fde-91ef-4a356a80f9fd.png">


second screenshot
<img width="269" alt="Screenshot 2021-12-14 at 6 34 49 PM" src="https://user-images.githubusercontent.com/2108309/146003683-bab502ef-a3d3-4b63-a666-198c9b3a52a3.png">

**Comment by vlussenburg** [comment]
If this is still a problem, please file a ticket via support.backtrace.io. Thanks!
