### ISSUE TITLE
Is navtive crash reports for windows standalone working?

### ISSUE THREAD

**Issue by micromang** [backtrace-labs/backtrace-unity#148]
Hi, 
I'm testing the native crash report of a Windows standalone build.
To force a crash for testing, I call Utils.ForceCrash(), which is one of the APIs provided by Unity.
I built and ran the app as Windows Standalone, and checked the crash termination.
And restarted the same app again. (Of course, the same crash is reproduced.)
Since then, however, the Backtrace web console has not updated any reports of any native crashes.

The following is a part of Player.Log:

```
...
Intentionally caused fatal error
Crash!!!
SymInit: Symbol-SearchPath: '.;E:\Output;E:\Output;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 534, UserName: 'jhmang'
OS-Version: 10.0.0
E:\Output\BacktraceTest.exe:BacktraceTest.exe (00007FF6C9420000), size: 675840 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2020.3.24.51085
C:\WINDOWS\SYSTEM32\ntdll.dll:ntdll.dll (00007FF96E880000), size: 2031616 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1533
C:\WINDOWS\System32\KERNEL32.DLL:KERNEL32.DLL (00007FF96CDA0000), size: 729088 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1500
C:\WINDOWS\System32\KERNELBASE.dll:KERNELBASE.dll (00007FF96B810000), size: 2772992 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1474
E:\Output\UnityPlayer.dll:UnityPlayer.dll (00007FF8F5A00000), size: 29196288 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2020.3.24.51085
C:\WINDOWS\System32\USER32.dll:USER32.dll (00007FF96E110000), size: 1654784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1316
...
========== OUTPUTTING STACK TRACE ==================

0x00007FF8F68DBB39 (UnityPlayer) DebugStringToFilePostprocessedStacktrace
0x00007FF8F68DB1A4 (UnityPlayer) DebugStringToFile
0x00007FF8F6272E7B (UnityPlayer) DiagnosticsUtils_Bindings::ForceCrash
0x00007FF8F639EFE7 (UnityPlayer) Utils_CUSTOM_ForceCrash
0x000001CE9F0F6B3A (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Diagnostics.Utils:ForceCrash (UnityEngine.Diagnostics.ForcedCrashCategory)
0x000001CE9F0EA153 (Mono JIT Code) GameMain/<Start>d__5:MoveNext ()
0x000001CE9F0E9E5C (Mono JIT Code) UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
...
========== END OF STACKTRACE ===========

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/jhmang/AppData/Local/Temp/DefaultCompany/BacktraceTest/Crashes

```

It was confirmed that crash.dmp and Player.log were created in the "C:/Users/jhmang/AppData/Local/Temp/DefaultCompany/BacktraceTest/Crashes" path. 
However, no reports are checked in the backtrace web-console dashboard.
I checked all the necessary options: native crash capture - Enabled, Filter or Skip Report - Disable, minidump type - Everything.
Of course managed exception reports are well updated.

Is native crash function for Window standalone working normally in backtrace-unity?
(My Unity version is 2020.3 and Backtrace-unity version is 3.7.3.)

**Comment by konraddysput** [comment]
Hey, today we recognized invalid behavior for windows standalone builds on x86 platforms. If you build and test your game on the x86 device, please wait until we land the pull request: https://github.com/backtrace-labs/backtrace-unity/pull/149 

Overall, the change described above is related to the different crash handler executables and it might be related to your problem but I'm not 100% sure this causes it. The reason why I think it's because we should also send data via Unity crash reporter executable. If you don't see crashes after your game restarts, can you verify the submission URL/database path? Do you also see any warnings generated by the backtrace-unity plugin in reports generated on the managed layer?

**Comment by vlussenburg** [comment]
Hello @micromang ,

If this is still an issue, could you please file a ticket at support.backtrace.io? Thanks!

Vincent.
