### ISSUE TITLE
DatabasePath not checked for permissions

### ISSUE THREAD

**Issue by vlussenburg** [backtrace-labs/backtrace-unity#25]
When providing a databasePath that the client does not have enough permissions on, the plugin keeps trying to create files and failing, resulting in a huge drop in performance.

`BacktraceConfiguration.ValidateDatabasePath` should check for appropriate permissions vs just check existence.

**Comment by konraddysput** [comment]
Not sure if the plugin should check the permissions - we should handle permissions in-game code. 

Instead I will propose to list all needed permissions in the README. What do you think @vlussenburg ?

**Comment by vlussenburg** [comment]
Maybe it's a bit much for us to do indeed. Let's close for now.
